//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace Movie.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.Favourites = new HashSet<Favourite>();
        }

        public int Id { get; set; }
        [Required]
        [RegularExpression("(.)+[@](.)+[.]([c][o][m]|([c][o][.](.)+))", ErrorMessage = "Invalid Email Format")]
        [Display(Name = "Email ID")]
        public string EmailID { get; set; }


        [Required]
        [RegularExpression("(.){6,}", ErrorMessage = "Minimum 6 characters.")]
        public string Username { get; set; }

        [Required]
        [RegularExpression("(.){6,}", ErrorMessage = "Password Length must atleast be 6 characters long.")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Required]
        [Display(Name = "Confirm password")]
        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage = "the password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
        //[Display(Name = "Register as an admin?")]
        public Nullable<int> IsAdmin { get; set; }
        public virtual ICollection<Favourite> Favourites
        {
            get; set;
        }
    }
}
