//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Movie.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Film
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Film()
        {
            this.Actors = new HashSet<Actor>();
        }
        [Key]
        public int MovieID { get; set; }
        public string Name { get; set; }
        public string Plot { get; set; }
        [Display(Name = "Year of Release")]
        public Nullable<int> Year_Of_Release { get; set; }
        [Display(Name = "Producer Name")]
        public Nullable<int> ProducerID { get; set; }
        public byte[] Poster { get; set; }

        public virtual Producer Producer { get; set; }
        [Required]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actor> Actors { get; set; }
    }
}
